version: "3"
services:
    postgres_db:
        build: ./
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "54320:5432"
        container_name: database
        expose: 
            - "54320"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
volumes:
    postgres_data:
